spring:
    application:
        name: client
    datasource:
        url: jdbc:mysql://localhost:3306/yeosu_mate
        username: root
        password: fuckDruid1!
    redis:
        data:
            host: localhost
            port: 6379

server:
    port: 8080
